---
- hosts: localhost
  become: true

  tasks:
  - name: stop container
    command: docker stop graffiter-user-service-instance
    ignore_errors: yes

  - name: remove container
    command: docker rm graffiter-user-service-instance
    ignore_errors: yes

  - name: build image
    command: docker build -t graffiter-user-service .

  - name: create container
    command: docker run --name graffiter-user-service-instance -d -p 8081:8081 --ulimit nofile=122880:122880 graffiter-user-service .
